projectA/accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('verify/',views.UserRegisterVerifyCodeView.as_view(),name='verify_code'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
]

projectA/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('',views.home,name='home'),

]

projectA/projectA/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),

]

projectA/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .manager import UserManager


class User(AbstractBaseUser):
   # email = models.EmailField(max_length=255,unique=True)
    phone_number = models.CharField(max_length=11,unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.full_name

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model): #one time password
    phone_number = models.CharField(max_length=11)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number}-{self.code}-{self.created}'

projectA/home/models.py
from django.db import models

# Create your models here.

projectA/accounts/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone_number','full_name', 'password')


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match !')
        return cd['password2']

    def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text='you can change password using <a href=\"../password/\">this form </a>')

    class Meta:
        model = User
        fields = ('full_name','phone_number','password','last_login')



class UserRegistrationForm(forms.Form):
    phone_number = forms.CharField(max_length=11)
    full_name = forms.CharField(label='full name')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']
        user = User.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('this phone number is exist.')
        return phone

    def clean_full_name(self):
        name = self.cleaned_data['full_name']
        user = User.objects.filter(full_name=name).exists()
        if user:
            raise ValidationError('this name is already exists.')
        return name



class VerifyCodeForm(forms.Form):
    code = forms.IntegerField()


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(max_length=11)
    password = forms.CharField(widget=forms.PasswordInput)

projectA/accounts/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import UserRegistrationForm,VerifyCodeForm,UserLoginForm
import random
from utils import send_Otp_Code
from .models import OtpCode,User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout


class UserRegisterView (View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'


    def get(self,request):
        form = self.form_class
        return render(request,self.template_name,{'form':form})  #send form to register page

    def post(self,request):
        form =self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000,9999)  #create random code
            send_Otp_Code(form.cleaned_data['phone_number'],random_code) #send phone number and code random to utils
            OtpCode.objects.create(phone_number=form.cleaned_data['phone_number'],code=random_code)
            request.session['user_registration_info'] = {
                'phone_number' : form.cleaned_data['phone_number'],
                'full_name' : form.cleaned_data['full_name'],
                'password' : form.cleaned_data['password'],
            }
            messages.success(request,'we send for you a code','success')
            return redirect('accounts:verify_code')
        return render(request,self.template_name,{'form':form})




class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm
    def get(self,request):
        form = self.form_class
        return render(request,'accounts/verify.html',{'form':form})

    def post(self,request):
        user_session = request.session['user_registration_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(user_session['phone_number'],
                                         user_session['full_name'],user_session['password'])
                code_instance.delete()
                messages.success(request,'you registered.','success')
                return redirect('home:home')

            else:
                messages.error(request,'this code is wrong...','danger')
                return redirect('accounts:verify_code')
        return redirect('home:home')



class UserLoginView(View):
    template_name = 'accounts/login.html'
    form_class = UserLoginForm
    def get(self,request):
        form = self.form_class
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,phone_number=cd['phone_number'],password=cd['password'])
            if user is not None:
                    login(request,user)
                    messages.success(request,'you login successfully...','success')
                    return redirect('home:home')

            messages.error(request, 'phone or password is wrong...', 'warning')

        return render(request,self.template_name,{'form':form})

class UserLogoutView(View):
    def get(self,request):
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('home:home')

projectA/home/views.py
from django.shortcuts import render


def home(request):
    return render(request,'home/home.html')

projectA/accounts/templates/accounts/login.html
{% extends 'base.html'  %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

{% endblock %}

projectA/accounts/templates/accounts/register.html
{% extends 'base.html'  %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>

{% endblock %}

projectA/accounts/templates/accounts/verify.html
{% extends 'base.html'  %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>

{% endblock %}

projectA/home/templates/home/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}


{% endblock %}

projectA/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>


<body>

        {% include 'inc/navbar.html' %}

        {% include 'inc/messages.html' %}
        {% block content %}  {% endblock %}


</body>


</html>

projectA/templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}

{% endif %}

projectA/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'home:home' %}">Home</a>

        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'accounts:user_logout' %}">LogOut</a>
        {% else %}
        <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
        <a class="nav-link active" href="{% url 'accounts:user_login' %}">LogIn</a>
        {% endif %}
        </div>

    </div>
</nav>